/**
 * ONS program tests (spec/ONS.md): ons-mirror VAA application and ons-registration
 * provisional claims, raw-instruction style (no IDL dependency), on the Anchor local
 * validator. Positive VAA / reconcile paths use the genesis fixtures generated by
 * scripts/generate-ons-fixtures.mjs; the Wormhole CPI boundary is exercised the same
 * way the announcer tests do (the core bridge is not on localnet).
 */
import { expect } from "chai";
import { createHash } from "node:crypto";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_CLOCK_PUBKEY,
  SYSVAR_RENT_PUBKEY,
  TransactionInstruction,
} from "@solana/web3.js";
import { keccak_256 } from "@noble/hashes/sha3";

import {
  connection,
  disc,
  payer,
  pda,
  send,
  sendExpectFail,
  str,
  u16le,
  u32le,
  u64le,
  WORMHOLE_CORE,
} from "./helpers";

const ONS_MIRROR = new PublicKey("D7EXuwcsGrUAYC6k69jrKvsKethsKYgR1pokkTcFvWsk");
const ONS_REGISTRATION = new PublicKey("5gfK9J8FJi3FpsQD33Hkrfwq8KqN4yadB2PDF9REnwMT");
const SYS = SystemProgram.programId;

// Must match scripts/generate-ons-fixtures.mjs.
const SOURCE_CHAIN_ETHEREUM = 2;
const ONS_EMITTER = Buffer.alloc(32, 7);
const PARENT_NAME = "opqtest.eth";
const SPEND = Buffer.concat([Buffer.from([2]), Buffer.alloc(32, 0x11)]);
const VIEW = Buffer.concat([Buffer.from([3]), Buffer.alloc(32, 0x22)]);
const ETH_OWNER = Buffer.alloc(20, 0x33);
const CLAIMER = Keypair.fromSeed(
  createHash("sha256").update("opaque-ons-claimer").digest(),
).publicKey;

const VAA_UPSERT = new PublicKey("CcqzakP2EaU9ozCyMh8vR83cpHGFMBXEmgoNxV6DC1tm");
const VAA_REVOKE = new PublicKey("7xZBQyK56UT7hfikpj89WVxXdNknuU89h9XwLWiJzDmw");
const VAA_STALE = new PublicKey("5AKQHMRw9fQHUDpWVScLCp8odKpB2LouC6ammi5h8Cjo");

const nameHash = (label: string): Buffer =>
  Buffer.from(keccak_256(`${label}.${PARENT_NAME}`));

const mirrorConfig = pda(ONS_MIRROR, [Buffer.from("config")]);
const mirrorRecord = (label: string) =>
  pda(ONS_MIRROR, [Buffer.from("ons_mirror"), nameHash(label)]);
const processedPda = (vaa: PublicKey) =>
  pda(ONS_MIRROR, [Buffer.from("processed"), vaa.toBuffer()]);
const registrationConfig = pda(ONS_REGISTRATION, [Buffer.from("config")]);
const claimPda = (label: string) =>
  pda(ONS_REGISTRATION, [Buffer.from("ons_claim"), nameHash(label)]);

function receiveRecordIx(vaa: PublicKey, hash: Buffer): TransactionInstruction {
  return new TransactionInstruction({
    programId: ONS_MIRROR,
    keys: [
      { pubkey: mirrorConfig, isSigner: false, isWritable: false },
      { pubkey: vaa, isSigner: false, isWritable: false },
      {
        pubkey: pda(ONS_MIRROR, [Buffer.from("ons_mirror"), hash]),
        isSigner: false,
        isWritable: true,
      },
      { pubkey: processedPda(vaa), isSigner: false, isWritable: true },
      { pubkey: payer.publicKey, isSigner: true, isWritable: true },
      { pubkey: SYS, isSigner: false, isWritable: false },
    ],
    data: Buffer.concat([disc("receive_record"), hash]),
  });
}

describe("ons-mirror", () => {
  it("initializes the config with the canonical registry emitter", async () => {
    await send([
      new TransactionInstruction({
        programId: ONS_MIRROR,
        keys: [
          { pubkey: mirrorConfig, isSigner: false, isWritable: true },
          { pubkey: payer.publicKey, isSigner: true, isWritable: true },
          { pubkey: SYS, isSigner: false, isWritable: false },
        ],
        data: Buffer.concat([
          disc("initialize"),
          u16le(SOURCE_CHAIN_ETHEREUM),
          ONS_EMITTER,
        ]),
      }),
    ]);
    const info = await connection.getAccountInfo(mirrorConfig);
    expect(info).to.not.be.null;
  });

  it("rejects a posted VAA not owned by the core bridge", async () => {
    const logs = await sendExpectFail([
      receiveRecordIx(payer.publicKey, nameHash("alice")),
    ]);
    expect(logs).to.include("NotWormholeOwned");
  });

  it("rejects a name_hash that does not match the payload", async () => {
    const logs = await sendExpectFail([
      receiveRecordIx(VAA_STALE, nameHash("mallory")),
    ]);
    expect(logs).to.include("NameHashMismatch");
  });

  it("applies an upsert VAA into the record PDA", async () => {
    await send([receiveRecordIx(VAA_UPSERT, nameHash("alice"))]);

    const info = await connection.getAccountInfo(mirrorRecord("alice"));
    expect(info).to.not.be.null;
    const data = info!.data;
    expect(data.subarray(8, 40).equals(nameHash("alice"))).to.equal(true);
    expect(data.subarray(40, 73).equals(SPEND)).to.equal(true);
    expect(data.subarray(73, 106).equals(VIEW)).to.equal(true);
    expect(data.subarray(106, 126).equals(ETH_OWNER)).to.equal(true);
    expect(data.readBigUInt64LE(158)).to.equal(11n); // wormhole_sequence
  });

  it("rejects a replayed VAA", async () => {
    const logs = await sendExpectFail([receiveRecordIx(VAA_UPSERT, nameHash("alice"))]);
    expect(logs).to.include("already in use"); // processed PDA exists
  });

  it("rejects a stale (lower-sequence) update for an existing record", async () => {
    const logs = await sendExpectFail([receiveRecordIx(VAA_STALE, nameHash("alice"))]);
    expect(logs).to.include("StaleSequence");
  });

  it("applies a revoke VAA by closing the record", async () => {
    await send([receiveRecordIx(VAA_REVOKE, nameHash("alice"))]);
    const info = await connection.getAccountInfo(mirrorRecord("alice"));
    expect(info).to.be.null;
  });
});

describe("ons-registration", () => {
  it("initializes the config with parent name and mirror program", async () => {
    await send([
      new TransactionInstruction({
        programId: ONS_REGISTRATION,
        keys: [
          { pubkey: registrationConfig, isSigner: false, isWritable: true },
          { pubkey: payer.publicKey, isSigner: true, isWritable: true },
          { pubkey: SYS, isSigner: false, isWritable: false },
        ],
        data: Buffer.concat([
          disc("initialize"),
          str(PARENT_NAME),
          ONS_MIRROR.toBuffer(),
        ]),
      }),
    ]);
    const info = await connection.getAccountInfo(registrationConfig);
    expect(info).to.not.be.null;
  });

  function claimIx(
    label: string,
    hash: Buffer,
    message: PublicKey,
  ): TransactionInstruction {
    const emitter = pda(ONS_REGISTRATION, [Buffer.from("emitter")]);
    const whPda = (seed: string) => pda(WORMHOLE_CORE, [Buffer.from(seed)]);
    const sequence = pda(WORMHOLE_CORE, [Buffer.from("Sequence"), emitter.toBuffer()]);
    return new TransactionInstruction({
      programId: ONS_REGISTRATION,
      keys: [
        { pubkey: registrationConfig, isSigner: false, isWritable: false },
        {
          pubkey: pda(ONS_REGISTRATION, [Buffer.from("ons_claim"), hash]),
          isSigner: false,
          isWritable: true,
        },
        { pubkey: payer.publicKey, isSigner: true, isWritable: true },
        { pubkey: emitter, isSigner: false, isWritable: false },
        { pubkey: whPda("Bridge"), isSigner: false, isWritable: true },
        { pubkey: whPda("fee_collector"), isSigner: false, isWritable: true },
        { pubkey: sequence, isSigner: false, isWritable: true },
        { pubkey: message, isSigner: true, isWritable: true },
        { pubkey: WORMHOLE_CORE, isSigner: false, isWritable: false },
        { pubkey: SYSVAR_CLOCK_PUBKEY, isSigner: false, isWritable: false },
        { pubkey: SYSVAR_RENT_PUBKEY, isSigner: false, isWritable: false },
        { pubkey: SYS, isSigner: false, isWritable: false },
      ],
      data: Buffer.concat([
        disc("claim"),
        hash,
        str(label),
        SPEND,
        VIEW,
        u32le(0), // batch_id
        u64le(0), // wormhole_fee
      ]),
    });
  }

  it("rejects an invalid label", async () => {
    const message = Keypair.generate();
    const logs = await sendExpectFail(
      [claimIx("Bad-Label", nameHash("Bad-Label"), message.publicKey)],
      [message],
    );
    expect(logs).to.include("InvalidLabel");
  });

  it("rejects a name_hash that does not match the label", async () => {
    const message = Keypair.generate();
    const logs = await sendExpectFail(
      [claimIx("carol", nameHash("not-carol"), message.publicKey)],
      [message],
    );
    expect(logs).to.include("NameHashMismatch");
  });

  it("claim validates and reaches the Wormhole CPI boundary", async () => {
    // The core bridge is not deployed on localnet, so the CPI must fail — but only
    // after the NameClaimed event is emitted, which proves label validation,
    // name-hash binding, PDA creation and payload encoding all passed.
    const message = Keypair.generate();
    const logs = await sendExpectFail(
      [claimIx("carol", nameHash("carol"), message.publicKey)],
      [message],
    );
    expect(logs).to.include("Program data:");
  });

  function reconcileIx(label: string, mirror: PublicKey): TransactionInstruction {
    return new TransactionInstruction({
      programId: ONS_REGISTRATION,
      keys: [
        { pubkey: registrationConfig, isSigner: false, isWritable: false },
        { pubkey: claimPda(label), isSigner: false, isWritable: true },
        { pubkey: CLAIMER, isSigner: false, isWritable: true },
        { pubkey: mirror, isSigner: false, isWritable: false },
        { pubkey: payer.publicKey, isSigner: true, isWritable: false },
      ],
      data: Buffer.concat([disc("reconcile"), nameHash(label)]),
    });
  }

  it("reconciles a confirmed claim (mirror record held by the claimer)", async () => {
    const before = await connection.getBalance(CLAIMER);
    await send([reconcileIx("bob-confirmed", mirrorRecord("bob-confirmed"))]);
    expect(await connection.getAccountInfo(claimPda("bob-confirmed"))).to.be.null;
    expect(await connection.getBalance(CLAIMER)).to.be.greaterThan(before); // rent refund
  });

  it("reconciles a lost claim (canonical chain registered another owner)", async () => {
    await send([reconcileIx("bob-lost", mirrorRecord("bob-lost"))]);
    expect(await connection.getAccountInfo(claimPda("bob-lost"))).to.be.null;
  });

  it("reconciles an expired claim after the pending window", async () => {
    await send([reconcileIx("bob-expired", mirrorRecord("bob-expired"))]);
    expect(await connection.getAccountInfo(claimPda("bob-expired"))).to.be.null;
  });

  it("refuses to reconcile a claim still inside the pending window", async () => {
    const logs = await sendExpectFail([
      reconcileIx("bob-pending", mirrorRecord("bob-pending")),
    ]);
    expect(logs).to.include("StillPending");
  });
});
